import { useState } from "react";
import { supabase } from "../supabaseClient";

function AIInput() {
  const [input, setInput] = useState("");

  // ✅ createTask defined here
  const createTask = async (title, priority) => {
    const { error } = await supabase.from("tasks").insert([
      {
        title,
        description: "Generated by AI",
        status: "pending",
        priority,
      },
    ]);

    if (error) console.error(error);
  };

  const generateTasks = async () => {
    const res = await fetch("http://localhost:5000/ai-tasks", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ input }),
    });

    const data = await res.json();

    console.log("AI Tasks:", data.tasks);

    // 🔥 insert into DB
    for (const task of data.tasks) {
      await createTask(task.title, task.priority);
    }
  };

  return (
    <div style={{ marginBottom: "20px" }}>
      <input
        type="text"
        placeholder="Enter your goal..."
        value={input}
        onChange={(e) => setInput(e.target.value)}
      />
      <button onClick={generateTasks}>Generate Tasks</button>
    </div>
  );
}

export default AIInput;